import { Recipe, Category } from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Breakfast",
    slug: "breakfast",
    description: "Start your day with a delicious morning meal",
    icon: "🍳",
    color: "#F59E0B",
    recipeCount: 12,
  },
  {
    id: "2",
    name: "Pasta",
    slug: "pasta",
    description: "Classic Italian pasta dishes and more",
    icon: "🍝",
    color: "#EF4444",
    recipeCount: 18,
  },
  {
    id: "3",
    name: "Salads",
    slug: "salads",
    description: "Fresh, vibrant salads for every occasion",
    icon: "🥗",
    color: "#10B981",
    recipeCount: 9,
  },
  {
    id: "4",
    name: "Soups",
    slug: "soups",
    description: "Warm and comforting soups and stews",
    icon: "🍲",
    color: "#8B5CF6",
    recipeCount: 14,
  },
  {
    id: "5",
    name: "Desserts",
    slug: "desserts",
    description: "Sweet endings and indulgent treats",
    icon: "🍰",
    color: "#EC4899",
    recipeCount: 22,
  },
  {
    id: "6",
    name: "Grilling",
    slug: "grilling",
    description: "BBQ and grilled perfection",
    icon: "🔥",
    color: "#F97316",
    recipeCount: 10,
  },
];

export const recipes: Recipe[] = [
  {
    id: "1",
    slug: "creamy-mushroom-pasta",
    title: "Creamy Mushroom Pasta",
    description:
      "A rich and velvety pasta dish with wild mushrooms, garlic, and fresh thyme in a decadent cream sauce.",
    image: "/images/mushroom-pasta.jpg",
    category: "Pasta",
    tags: ["vegetarian", "quick", "comfort food"],
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    featured: true,
    author: "Chef Maria",
    createdAt: "2024-01-15",
    ingredients: [
      { name: "pasta", amount: "400", unit: "g" },
      { name: "mixed mushrooms", amount: "300", unit: "g" },
      { name: "heavy cream", amount: "200", unit: "ml" },
      { name: "garlic cloves", amount: "3" },
      { name: "fresh thyme", amount: "2", unit: "sprigs" },
      { name: "parmesan", amount: "50", unit: "g" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "salt & pepper", amount: "to taste" },
    ],
    steps: [
      "Cook pasta in salted boiling water until al dente. Reserve 1 cup pasta water.",
      "Slice mushrooms and mince garlic.",
      "Heat olive oil in a large pan. Sauté garlic for 1 minute, then add mushrooms.",
      "Cook mushrooms until golden, about 8 minutes. Season well.",
      "Add cream and thyme, simmer for 3 minutes until slightly thickened.",
      "Toss with pasta, adding pasta water to loosen as needed.",
      "Finish with grated parmesan and serve immediately.",
    ],
    nutrition: { calories: 520, protein: 18, carbs: 62, fat: 24 },
  },
  {
    id: "2",
    slug: "avocado-toast-eggs",
    title: "Avocado Toast with Poached Eggs",
    description:
      "The ultimate brunch staple — creamy smashed avocado on sourdough topped with perfectly poached eggs and chili flakes.",
    image: "/images/avocado-toast.jpg",
    category: "Breakfast",
    tags: ["vegetarian", "brunch", "healthy"],
    difficulty: "Medium",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    featured: true,
    author: "Chef James",
    createdAt: "2024-02-01",
    ingredients: [
      { name: "sourdough bread", amount: "2", unit: "slices" },
      { name: "ripe avocados", amount: "2" },
      { name: "eggs", amount: "2" },
      { name: "lemon juice", amount: "1", unit: "tsp" },
      { name: "chili flakes", amount: "pinch" },
      { name: "everything bagel seasoning", amount: "1", unit: "tsp" },
      { name: "white vinegar", amount: "1", unit: "tbsp" },
    ],
    steps: [
      "Toast sourdough until golden and crisp.",
      "Mash avocados with lemon juice, salt, and pepper.",
      "Bring a pan of water to a gentle simmer with vinegar.",
      "Crack eggs into a fine mesh strainer, then slide into water. Poach 3 minutes.",
      "Spread avocado on toast, top with poached egg.",
      "Sprinkle with chili flakes and bagel seasoning. Serve immediately.",
    ],
    nutrition: { calories: 380, protein: 14, carbs: 32, fat: 22 },
  },
  {
    id: "3",
    slug: "classic-caesar-salad",
    title: "Classic Caesar Salad",
    description:
      "A timeless Caesar with house-made dressing, crispy homemade croutons, and generous shavings of aged parmesan.",
    image: "/images/caesar-salad.jpg",
    category: "Salads",
    tags: ["classic", "appetizer", "crowd-pleaser"],
    difficulty: "Medium",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    featured: false,
    author: "Chef Maria",
    createdAt: "2024-02-10",
    ingredients: [
      { name: "romaine lettuce", amount: "2", unit: "heads" },
      { name: "parmesan", amount: "80", unit: "g" },
      { name: "sourdough bread", amount: "2", unit: "slices" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "anchovies", amount: "4", unit: "fillets" },
      { name: "egg yolk", amount: "1" },
      { name: "Dijon mustard", amount: "1", unit: "tsp" },
      { name: "lemon juice", amount: "2", unit: "tbsp" },
      { name: "Worcestershire sauce", amount: "1", unit: "tsp" },
      { name: "olive oil", amount: "80", unit: "ml" },
    ],
    steps: [
      "Make croutons: cube bread, toss with olive oil and garlic, bake at 200°C for 10 minutes.",
      "Make dressing: blend anchovies, garlic, egg yolk, mustard, and lemon juice.",
      "Slowly whisk in olive oil until emulsified. Add Worcestershire, season.",
      "Tear romaine into large pieces, toss with dressing.",
      "Top with croutons and shaved parmesan. Serve immediately.",
    ],
    nutrition: { calories: 290, protein: 12, carbs: 18, fat: 20 },
  },
  {
    id: "4",
    slug: "french-onion-soup",
    title: "French Onion Soup",
    description:
      "A soul-warming classic with deeply caramelized onions in rich beef broth, topped with crusty bread and bubbling gruyère.",
    image: "/images/french-onion-soup.jpg",
    category: "Soups",
    tags: ["classic", "comfort food", "winter"],
    difficulty: "Medium",
    prepTime: 20,
    cookTime: 90,
    servings: 4,
    featured: true,
    author: "Chef Paul",
    createdAt: "2024-01-28",
    ingredients: [
      { name: "yellow onions", amount: "1", unit: "kg" },
      { name: "beef stock", amount: "1.5", unit: "L" },
      { name: "dry white wine", amount: "150", unit: "ml" },
      { name: "butter", amount: "50", unit: "g" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "baguette", amount: "4", unit: "slices" },
      { name: "gruyère cheese", amount: "200", unit: "g" },
      { name: "fresh thyme", amount: "3", unit: "sprigs" },
      { name: "bay leaf", amount: "1" },
    ],
    steps: [
      "Thinly slice onions. Melt butter with oil in a heavy-bottomed pot over medium heat.",
      "Add onions and cook slowly for 45-60 minutes until deep golden brown, stirring often.",
      "Add wine and cook until evaporated. Add stock, thyme, bay leaf.",
      "Simmer 20 minutes. Season generously.",
      "Ladle into oven-safe bowls. Top with baguette slices and gruyère.",
      "Broil until cheese is bubbling and golden. Serve immediately.",
    ],
    nutrition: { calories: 420, protein: 20, carbs: 34, fat: 22 },
  },
  {
    id: "5",
    slug: "chocolate-lava-cake",
    title: "Chocolate Lava Cake",
    description:
      "Individual dark chocolate cakes with a molten, gooey centre. An indulgent dessert that never fails to impress.",
    image: "/images/lava-cake.jpg",
    category: "Desserts",
    tags: ["chocolate", "indulgent", "dinner party"],
    difficulty: "Medium",
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    featured: true,
    author: "Chef Sophie",
    createdAt: "2024-02-14",
    ingredients: [
      { name: "dark chocolate (70%)", amount: "200", unit: "g" },
      { name: "butter", amount: "100", unit: "g" },
      { name: "eggs", amount: "4" },
      { name: "egg yolks", amount: "2" },
      { name: "caster sugar", amount: "120", unit: "g" },
      { name: "plain flour", amount: "40", unit: "g" },
      { name: "cocoa powder for dusting", amount: "2", unit: "tbsp" },
      { name: "vanilla extract", amount: "1", unit: "tsp" },
    ],
    steps: [
      "Preheat oven to 200°C. Butter and dust 4 ramekins with cocoa powder.",
      "Melt chocolate and butter together until smooth. Let cool slightly.",
      "Whisk eggs, yolks, and sugar until pale and thick.",
      "Fold chocolate mixture into eggs, then fold in flour gently.",
      "Divide batter into ramekins. Can be refrigerated at this point.",
      "Bake 10-12 minutes until edges are set but centre jiggles slightly.",
      "Invert onto plates immediately. Serve with vanilla ice cream.",
    ],
    nutrition: { calories: 580, protein: 10, carbs: 52, fat: 38 },
  },
  {
    id: "6",
    slug: "grilled-lemon-herb-chicken",
    title: "Grilled Lemon Herb Chicken",
    description:
      "Juicy, smoky grilled chicken marinated in lemon, garlic, and fresh herbs. Perfect for summer cookouts.",
    image: "/images/grilled-chicken.jpg",
    category: "Grilling",
    tags: ["protein", "summer", "gluten-free"],
    difficulty: "Easy",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    featured: false,
    author: "Chef James",
    createdAt: "2024-03-01",
    ingredients: [
      { name: "chicken thighs", amount: "8", unit: "pieces" },
      { name: "lemon", amount: "2" },
      { name: "garlic", amount: "4", unit: "cloves" },
      { name: "fresh rosemary", amount: "2", unit: "sprigs" },
      { name: "fresh thyme", amount: "4", unit: "sprigs" },
      { name: "olive oil", amount: "4", unit: "tbsp" },
      { name: "smoked paprika", amount: "1", unit: "tsp" },
      { name: "salt & pepper", amount: "to taste" },
    ],
    steps: [
      "Combine lemon zest, lemon juice, minced garlic, herbs, paprika, and oil.",
      "Score chicken thighs and coat in marinade. Refrigerate 2+ hours.",
      "Heat grill to medium-high. Remove chicken from marinade.",
      "Grill skin-side down 8-10 minutes until charred and crispy.",
      "Flip and cook another 10-12 minutes until cooked through (74°C internal).",
      "Rest 5 minutes before serving. Garnish with fresh herbs and lemon wedges.",
    ],
    nutrition: { calories: 380, protein: 42, carbs: 4, fat: 22 },
  },
];

export const getFeaturedRecipes = (): Recipe[] =>
  recipes.filter((r) => r.featured);

export const getRecipeBySlug = (slug: string): Recipe | undefined =>
  recipes.find((r) => r.slug === slug);

export const getRecipesByCategory = (category: string): Recipe[] =>
  recipes.filter(
    (r) => r.category.toLowerCase() === category.toLowerCase()
  );

export const searchRecipes = (query: string): Recipe[] => {
  const q = query.toLowerCase();
  return recipes.filter(
    (r) =>
      r.title.toLowerCase().includes(q) ||
      r.description.toLowerCase().includes(q) ||
      r.tags.some((t) => t.toLowerCase().includes(q)) ||
      r.category.toLowerCase().includes(q)
  );
};
